---
title: "cort_rate"
author: "A Torrico"
date: '2022-11-01'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#install.packages("Rtools")
#install.packages("tidyverse")
#install.packages("here")
#install.packages("janitor")
#install.packages("dplyr")
#install.packages("lme4", type="binary")
#install.packages("sjlabelled")
#install.packages("sjPlot")
#install.packages("sjmisc")
#install.packages("Matrix")

library(tidyverse)
library(here)
library(janitor)
library(dplyr)
library(ggplot2)
library(lme4)
library(sjPlot)
library(sjmisc)
library(sjlabelled)
library(Matrix)
```

#calling the data and clean names to make everything lowercase
```{r}
cort_rt <- read.csv(here("data", "corrected-CORT levels for RT 2012-2015.csv")) %>%
  clean_names()
ucp_rt <- read.csv(here("data", "UCP data for RT 2012-2015.csv")) %>%
  clean_names()
alarm_ige <- read.csv(here("data", "Alarm and IGEs for RT 2012-2015.csv")) %>%
  clean_names()
chomp_rt <- read.csv(here("data", "CHomp for RT 2012-2015.csv")) %>%
  clean_names()
psa_rt <- read.csv(here("data", "PSAs for RT 2012-2015 - per Day.csv")) %>%
  clean_names()
repro <- read.csv(here("data", "Repro for RT 2012-2015.csv")) %>%
  clean_names()
```

```{r}
repro <- repro %>%
  mutate(repro_narrow = case_when(pregnant=="1" ~ "1",
                                  d_infant == "1" ~ "2",
                                  pregnant == "0" ~ "0",))
repro <- repro %>%
  mutate(repro_broad = case_when(pregnant =="1" ~ "1" ,
                             d_infant == "1" ~ "2",
                            pregnant == "0" ~ "0",
                            pregnant == "10" ~ "1"))

```



#selecting columns from each dataset
```{r}
selected_alarm <- select(alarm_ige, group, r_eagle, r_ig_es, wo_p)
selected_chomp <- select(chomp_rt, group, c_homp_final, wo_p)
selected_cort <- select(cort_rt, species, group, name, class, cort_dw, wo_p, date, time)
#renaming wp in psa to w_op to match all other datasets
colnames(psa_rt)[4]<-"wo_p"
selected_psa <- select(psa_rt, psa_my_perc, psa_bl_perc, psa_ch_perc, wo_p, group, date)
selected_ucp <- select(ucp_rt, group, name, mean_uc_psg, wo_p)
selected_repro <- repro%>%
  select(repro_narrow, repro_broad, wo_p, group, name)
```


#cortisol average by group
```{r}
selected_cort$cort_dw <- gsub(",", "", selected_cort$cort_dw)

cort_dw_num <- as.numeric(selected_cort$cort_dw)

selected_cort$cort_numeric <- c(cort_dw_num)
  


rename_selected_cort <- selected_cort %>%
  group_by(group) %>%
  summarize(cort_sum=sum(cort_dw_num))

  
```


#combining selected columns datasets
```{r}
cort_psa <- full_join(x=selected_cort, y=selected_psa, by=c("wo_p","group", "date"))%>%
  drop_na(cort_dw)
cort_psa_alarm <- full_join(x=cort_psa, y=selected_alarm, by=c("wo_p","group"))
cort_alarm_psa_repro <- full_join(x=cort_psa_alarm, y=selected_repro, by=c("wo_p", "group", "name"))
cort_alarm_psa_repro_ucp <-full_join(x=cort_alarm_psa_repro, y=selected_ucp, by=c("wo_p","group","name"))%>%
  drop_na(cort_dw)

 
final <- cort_alarm_psa_repro_ucp 

```



#trying ggplt gg cort dw x r eagle
```{r}
ggplot(data = final, aes(x=r_eagle, y=cort_numeric)) +
  geom_point()
```


```{r}
ggplot(data = final, aes(x=wo_p, y=r_eagle, color=group)) +
  geom_point()+
  theme_gray()
```
```{r}
ggplot(data = final, aes(x=wo_p, y=psa_ch_perc, color=group)) +
  geom_point()
```
```{r}
ggplot(data = final, aes(x=wo_p, y=psa_my_perc, color = group)) +
  geom_point() +
  theme_gray()
```
```{r}

ggplot(final, aes(x=group, y=r_eagle)) +
  geom_boxplot()+
  theme_gray()

```

```{r}
ggplot(final, aes(x=group, y=psa_ch_perc)) +
  geom_boxplot()+
  theme_gray()
```
```{r}
ggplot(final, aes(x=group, y=psa_my_perc)) +
  geom_boxplot()+
  theme_gray()
```

#model
```{r}
model_group <- lmer(cort_numeric ~ r_eagle + psa_ch_perc + mean_uc_psg + psa_my_perc+
  (1|group), data=final)
  
summary(model_1)

tab_model(model_group, show.aic = TRUE, p.style = "numeric", emph.p = TRUE)
```

```{r}
model_group_name <- lmer(cort_numeric ~ r_eagle + psa_ch_perc + mean_uc_psg + psa_my_perc+
  (1|group /name), data=final)

tab_model(model_group_name, show.aic = TRUE, p.style = "numeric", emph.p = TRUE)
```



```{r}
model_2 <- lmer(cort_numeric ~ r_eagle + psa_ch_perc * mean_uc_psg + psa_my_perc+
  (1|group /name), data=final)

model_3 <- lmer(cort_numeric ~ r_eagle + psa_ch_perc + mean_uc_psg * psa_my_perc+
  (1|group /name), data=final)


tab_model(model_2 , model_3, show.aic = TRUE, p.style = "numeric", emph.p = TRUE)
#note
```

```{r}
 # something else to push to git

class(final$cort_dw)
final$cort_dw <- gsub(",", "", final$cort_dw)
```



```{r}
model_4 <- lmer(cort_numeric ~ r_eagle * mean_uc_psg + psa_my_perc + psa_ch_perc +
  (1|group /name), data=final)

tab_model(model_4, show.aic = TRUE, p.style = "numeric", emph.p = TRUE)

ggplot(final, aes(x= mean_uc_psg, y= cort_dw))+
         geom_point()+
  geom_smooth(method = "lm")

write.csv(final, "final.csv", na = "")

model_6 <- lmer(cort_numeric ~ r_eagle +
  (1|group /name), data=final)
tab_model(model_6, show.aic = TRUE, p.style = "numeric", emph.p = TRUE)
```



```{r}
#time 
model_time <- lmer(cort_numeric ~ r_eagle + psa_ch_perc + mean_uc_psg + psa_my_perc+
  (1|group /name/ time), data=final)
tab_model(model_time, show.aic = TRUE, p.style = "numeric", emph.p = TRUE)

```

```{r}
#mean cort per monkey 
mean_cort<- aggregate(data=final, cort_numeric~name, FUN=mean)

final_df <-merge(x=final, y=mean_cort, by=("name"))

final_df$centered_cort<-(final_df$cort_numeric.x-final_df$cort_numeric.y) 
```

```{r}
#model with mean cort 
model_7 <- lmer(centered_cort ~ r_eagle + psa_ch_perc + mean_uc_psg + psa_my_perc+
  (1|group /name/ time), data=final_df)
tab_model(model_7, show.aic = TRUE, p.style = "numeric", emph.p = TRUE)
```


```{r}
#standardizing psa_ch_perc
final_df$mean_psachperc<-mean(final_df$psa_ch_perc, na.rm=TRUE)

final_df$sd_psachperc<-sd(final_df$psa_ch_perc, na.rm=TRUE)

final_df$stan_psachperc<-((final_df$psa_ch_perc - final_df$mean_psachperc)-(2*final_df$sd_psachperc))
```


```{r}
#standardizing reagle
final_df$mean_reagle<-mean(final_df$r_eagle, na.rm=TRUE)

final_df$sd_reagle<-sd(final_df$r_eagle, na.rm=TRUE)

final_df$stan_reagle<-((final_df$r_eagle - final_df$mean_reagle)-(2*final_df$sd_reagle))
```


```{r}
#standardizing psa_my_perc
final_df$mean_psamyperc<-mean(final_df$psa_my_perc, na.rm=TRUE)

final_df$sd_psamyperc<-sd(final_df$psa_my_perc, na.rm=TRUE)

final_df$stan_psamyperc<-((final_df$psa_my_perc - final_df$mean_psamyperc)-(2*final_df$sd_psamyperc))
```


```{r}
#standardizing mean_uc_psg
final_df$mean_mean_uc_psg<-mean(final_df$mean_uc_psg, na.rm=TRUE)

final_df$sd_mean_uc_psg<-sd(final_df$mean_uc_psg, na.rm=TRUE)

final_df$stan_mean_uc_psg<-((final_df$mean_uc_psg - final_df$mean_mean_uc_psg)-(2*final_df$sd_mean_uc_psg))
```

```{r}
#standardized model
model_8 <- lmer(centered_cort ~ stan_reagle + stan_psachperc + stan_mean_uc_psg + stan_psamyperc+ 
  (1|name), data=final_df)
tab_model(model_8, show.aic = TRUE, p.style = "numeric", emph.p = TRUE)

write.csv(final_df, "final_df3.15.csv", na = "")

model_9 <- lmer(centered_cort ~ stan_reagle + stan_psachperc + stan_mean_uc_psg + stan_psamyperc+
  (1|group /name/ time), data=final_df)
tab_model(model_7, show.aic = TRUE, p.style = "numeric", emph.p = TRUE)
```


```{r}
#time as number
time_str<- as.character(final_df$time)

time_obj<- as.POSIXct(time_str, format= "%H: %M")

final_df$time_num<- as.numeric(time_obj)


final_df$timess<- gsub(":","",final_df$time)
class(final_df$timess)
final_df$timess<-as.numeric(final_df$timess)

model_10 <- lmer(centered_cort ~ stan_reagle + stan_psachperc + stan_mean_uc_psg + stan_psamyperc + timess + repro_broad +
  (1|name), data=final_df)
tab_model(model_10, show.aic = TRUE, p.style = "numeric", emph.p = TRUE)
```




```{r}
null_model <- lmer(cort_numeric.x~ cort_numeric.y + mean_uc_psg + timess + repro_broad +
                     (1|wo_p/name), data=final_df)
tab_model(null_model, show.aic = TRUE, p.style = "numeric", emph.p = TRUE)
```

